# Use the nl80211 driver with the brcmfmac driver
driver=nl80211

# NOTE: hw_mode, channel, ieee80211n/ieee80211ac, ht_capab, vht_capab,
# country_code and ieee80211d are appended by run.sh based on the
# `band` (2.4 / 5) and `channel` options.

# Enable WMM
wmm_enabled=1

# Bit field: 1=wpa, 2=wep, 3=both
auth_algs=1

# Use WPA2
wpa=2

# Use a pre-shared key
wpa_key_mgmt=WPA-PSK

# Use AES, instead of TKIP
rsn_pairwise=CCMP

# hostapd event logger configuration
logger_stdout=-1
logger_stdout_level=2
